# Generated by Django 4.2.11 on 2024-04-23 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('cid', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('type', models.IntegerField(choices=[(1, 'Truck'), (2, 'Sedan')])),
                ('active', models.BooleanField(default=True)),
                ('address', models.CharField(max_length=500)),
                ('age', models.IntegerField(max_length=3)),
                ('issuedate', models.DateField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('url', models.URLField()),
            ],
        ),
    ]
