# Generated by Django 4.2.11 on 2024-04-23 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('oid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('gender', models.IntegerField(choices=[(1, 'Male'), (2, 'Female')])),
            ],
        ),
        migrations.AlterField(
            model_name='car',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='cid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
